header:
  version : 1

repos:
  meta-mender-kernel:

  meta-bitbake-variable-substitution:
    url    : "https://github.com/coreycothrum/meta-bitbake-variable-substitution.git"
    refspec: 0043a84fab9abc33e2fec6fbae120eee1b733bb9

  meta-mender:
    url    : "https://github.com/mendersoftware/meta-mender.git"
    refspec: 133e86f0255f77b3a9e967810327979b572e0cfd
    layers :
      meta-mender-core:

  poky:
    url    : "https://git.yoctoproject.org/git/poky"
    refspec: 94d917219993b45b9d69a87aba1b69a6ca8f4d1e
    layers :
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url    : "https://github.com/openembedded/meta-openembedded.git"
    refspec: 50d4a8d2a983a68383ef1ffec2c8e21adf0c1a79
    layers :
      meta-oe:
