header:
  version : 1

repos:
  meta-mender-kernel:

  meta-bitbake-variable-substitution:
    url    : "https://github.com/coreycothrum/meta-bitbake-variable-substitution.git"
    refspec: e67ebb441a694f0c273cf681ab8ab05c5c1d2be2

  meta-mender:
    url    : "https://github.com/mendersoftware/meta-mender.git"
    refspec: f830d2c54145a61286f8b29d1125b88b782612c9
    layers :
      meta-mender-core:

  poky:
    url    : "https://git.yoctoproject.org/git/poky"
    refspec: 98d21218fcf1449d31368bf6216fcc2eebb0f529
    layers :
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url    : "https://github.com/openembedded/meta-openembedded.git"
    refspec: 95969f0f5f4264644a5dbfb6d4fb66e2ac3a2cde
    layers :
      meta-oe:
