header:
  version : 1

repos:
  meta-mender-kernel:

  meta-bitbake-variable-substitution:
    url    : "https://github.com/coreycothrum/meta-bitbake-variable-substitution.git"
    refspec: 0043a84fab9abc33e2fec6fbae120eee1b733bb9

  meta-mender:
    url    : "https://github.com/mendersoftware/meta-mender.git"
    refspec: bd64bbc28517d1ab07bfa225f8cad16beda167aa
    layers :
      meta-mender-core:

  poky:
    url    : "https://git.yoctoproject.org/git/poky"
    refspec: 4a88ada88fa54587e373fb2b831466648433f6a8
    layers :
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url    : "https://github.com/openembedded/meta-openembedded.git"
    refspec: 50d4a8d2a983a68383ef1ffec2c8e21adf0c1a79
    layers :
      meta-oe:
