header:
  version : 1

repos:
  meta-mender-kernel:

  meta-bitbake-variable-substitution:
    url    : "https://github.com/coreycothrum/meta-bitbake-variable-substitution.git"
    refspec: e67ebb441a694f0c273cf681ab8ab05c5c1d2be2

  meta-mender:
    url    : "https://github.com/coreycothrum/meta-mender.git"
    refspec: f9034faf3128394f7ca95f16670e91c031699e53
    layers :
      meta-mender-core:

  poky:
    url    : "https://git.yoctoproject.org/git/poky"
    refspec: d20ef1f5a5de7820b3e9b7f539b51f94954e9cd5
    layers :
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url    : "https://github.com/openembedded/meta-openembedded.git"
    refspec: f12e852c56ca897139220894d8b41e7967a70a58
    layers :
      meta-oe:
