header:
  version : 1

repos:
  meta-mender-kernel:

  meta-bitbake-variable-substitution:
    url    : "https://github.com/coreycothrum/meta-bitbake-variable-substitution.git"
    refspec: 0043a84fab9abc33e2fec6fbae120eee1b733bb9

  meta-mender:
    url    : "https://github.com/mendersoftware/meta-mender.git"
    refspec: 53991d0f66ac5ae8ede77f25169a6cd545d0b9e5
    layers :
      meta-mender-core:

  poky:
    url    : "https://git.yoctoproject.org/git/poky"
    refspec: 8c489602f218bcf21de0d3c9f8cf620ea5f06430
    layers :
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url    : "https://github.com/openembedded/meta-openembedded.git"
    refspec: a47ef046619d639dfbd3be2a13ef6d5b40fd40a1
    layers :
      meta-oe:
