header:
  version : 1

repos:
  meta-mender-kernel:

  meta-bitbake-variable-substitution:
    url    : "https://github.com/coreycothrum/meta-bitbake-variable-substitution.git"
    refspec: 0043a84fab9abc33e2fec6fbae120eee1b733bb9

  meta-mender:
    url    : "https://github.com/mendersoftware/meta-mender.git"
    refspec: 9166e577fa3f0fbac50d6bc9bb497ad37a4c4952
    layers :
      meta-mender-core:

  poky:
    url    : "https://git.yoctoproject.org/git/poky"
    refspec: 30656ea54de82cabb818f07af711b96211421c95
    layers :
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url    : "https://github.com/openembedded/meta-openembedded.git"
    refspec: 82c75b466e55d7dca7a2364986ecb704cf63d141
    layers :
      meta-oe:
