header:
  version : 1

repos:
  meta-mender-kernel:

  meta-bitbake-variable-substitution:
    url    : "https://github.com/coreycothrum/meta-bitbake-variable-substitution.git"
    refspec: e67ebb441a694f0c273cf681ab8ab05c5c1d2be2

  meta-mender:
    url    : "https://github.com/mendersoftware/meta-mender.git"
    refspec: 75b51d94058412e47c3fd94eeede86c407711f44
    layers :
      meta-mender-core:

  poky:
    url    : "https://git.yoctoproject.org/git/poky"
    refspec: 0839888394a6e42e96f9f0d201376eb38bc79b24
    layers :
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url    : "https://github.com/openembedded/meta-openembedded.git"
    refspec: 7889158dcd187546fc5e99fd81d0779cad3e8d17
    layers :
      meta-oe:
