header:
  version : 1

repos:
  meta-mender-kernel:

  meta-bitbake-variable-substitution:
    url    : "https://github.com/coreycothrum/meta-bitbake-variable-substitution.git"
    refspec: e67ebb441a694f0c273cf681ab8ab05c5c1d2be2

  meta-mender:
    url    : "https://github.com/mendersoftware/meta-mender.git"
    refspec: 045cfcfc3649b0505cee0b56af8946ef692cd67d
    layers :
      meta-mender-core:

  poky:
    url    : "https://git.yoctoproject.org/git/poky"
    refspec: 795339092f87672e4f68e4d3bc4cfd0e252d1831
    layers :
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url    : "https://github.com/openembedded/meta-openembedded.git"
    refspec: 69f94af4d91215e7d4e225bab54bf3bcfee42f1c
    layers :
      meta-oe:
